Repository kubevirt/libvirt, pull requests merged in 2019-11, with the labels that each got.

#32 Unify Dockerfiles
  .travis.yml
  Dockerfile
  Dockerfile.ppc64le
Labels: dco-signoff: yes, size/M

#35 Fix image generation
  .travis.yml
  Dockerfile
  README.md
  build.sh
  config
  deploy.sh
  docker-config.json
  publish.sh
  rmtag.sh
Labels: dco-signoff: yes, size/L

#36 Additional cleanups
  .travis.yml
  Dockerfile
  build.sh
Labels: dco-signoff: yes, size/S

#37 Minimize libvirt installation
  Dockerfile
Labels: dco-signoff: yes, size/XS

#38 Fix and improve README
  README.md
Labels: dco-signoff: yes, size/S

#39 Update to libvirt 5.6.0
  .travis.yml
  Dockerfile
  augconf
  build.sh
  config
Labels: dco-signoff: yes, size/S
