Repository kubevirt/libvirt, pull requests merged in 2019-04, with the labels that each got.

#22 Dockerfile: Use libvirt-5.1.0
  Dockerfile
  build.sh
  publish.sh
Labels: size/XS

#21 Add support for ppc64le
  .travis.yml
  Dockerfile.ppc64le
Labels: size/M

#23 ppc64le: use latest libvirt
  Dockerfile.ppc64le
Labels: size/S
