Repository kubevirt/libvirt, pull requests merged in 2020-05, with the labels that each got.

#50 bump libvirt to 6.0.0 and drop PPC
  .travis.yml
  config
Labels: dco-signoff: yes, size/S

#51 Deploy from av-* branches
  .travis.yml
Labels: dco-signoff: yes, size/XS

#52 README: Explain that master should not be used
  .gitignore
  .travis.yml
  Dockerfile
  LICENSE
  README.md
  augconf
  build.sh
  config
  deploy.sh
  docker-config.json
  libvirtd.sh
  rmtag.sh
Labels: dco-signoff: yes, size/XL

#53 Switch to buildx + qemu-static for building and deploying
  .gitignore
  .travis.yml
  Dockerfile.in
  build.sh
  deploy.sh
  hack/build.sh
  hack/config
  hack/deploy.sh
  hack/docker-client.json
  hack/docker-daemon.json
  hack/prepare.sh
  rmtag.sh
Labels: dco-signoff: yes, size/L

#46 Fix the examples in the README.md
  README.md
Labels: dco-signoff: yes, size/S

#45 Add CONTRIBUTING.md
  CONTRIBUTING.md
Labels: dco-signoff: yes, size/XS
