Repository kubevirt/libvirt, pull requests merged in 2020-11, with the labels that each got.

#63 config: Bump QEMU and libvirt versions
  hack/config
Labels: dco-signoff: yes, size/XS

#64 dockerfile: Reformat
  Dockerfile.in
Labels: dco-signoff: yes, size/S

#62 Drop libvirtd.sh
  Dockerfile.in
  README.md
  augconf
  libvirtd.sh
Labels: dco-signoff: yes, size/L

#65 Add more build types
  .travis.yml
  README.md
  hack/build.sh
  hack/common.sh
  hack/config
  hack/deploy.sh
  hack/local-build.sh
  hack/prepare.sh
  hack/simple-build.sh
Labels: dco-signoff: yes, size/L

#67 Add seabios 1.14.0
  Dockerfile.in
  hack/common.sh
  hack/config
Labels: dco-signoff: yes, size/XS

#68 Add dependency to get the sysctl binary
  Dockerfile.in
Labels: dco-signoff: yes, size/XS

#69 Add findutils to have the find binary available
  Dockerfile.in
Labels: dco-signoff: yes, size/XS
